### ISSUE TITLE
CSRF protection in ueberauth breaks Slack strategy

### ISSUE THREAD

**Issue by MMore** [jsmestad/ueberauth_slack_v2#3]
Hello,

I've noticed that this strategy breaks with https://github.com/ueberauth/ueberauth/pull/136 in v0.7.0 in `ueberauth`. You always get the following error: 

```
%Ueberauth.Failure.Error{
    message: "Cross-Site Request Forgery attack",
    message_key: :csrf_attack
 }
```

Downgrading to v0.6.3 works (as temporary workaround).

**Comment by jsmestad** [comment]
Yeah I have not had a chance to test 0.7.0. If you figure out the cause, :pray: please PR it and I can get it merged in.

**Comment by jsmestad** [comment]
@MMore I pushed out a change that, according to the Ueberauth CSRF commit, should allow this strategy to keep working.

**Comment by MMore** [comment]
Thanks a lot for fixing the blocking issue and allow upgrading to a newer version!

As this fix basically disables the CSRF protection, I'd recommend adding another issue to implement it properly as `Ueberauth` states in their source code:

> By default strategies must implement https://tools.ietf.org/html/rfc6749#section-10.12
  if you wish to disable this feature, you can use the `:ignores_csrf_attack` option:
> We strongly recommend never disabling this feature, unless you have some technical
  limitations that forces you to do so.
https://github.com/ueberauth/ueberauth/blob/1e67842a41da850b8f671ac6a052acd8e2ce810d/lib/ueberauth/strategy.ex#L263

**Comment by jsmestad** [comment]
Yeah I agree that is a better approach for the future. I won't have the bandwidth to add the functionality but definitely welcome PRs that do
